#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace Engine
{
	// ID_DYNAMIC : 실시간 업데이트가 필요한 컴포넌트
	enum COMPONENTID { ID_DYNAMIC, ID_STATIC, ID_END };
	//윈 모드
	enum WINMODE { MODE_FULL, MODE_WIN };
	//TRANSFORM에서 쓰는 것
	enum INFO { INFO_RIGHT, INFO_UP, INFO_LOOK, INFO_POS, INFO_END };
	//Transform에서 씀
	enum ROTATION { ROT_X, ROT_Y, ROT_Z, ROT_END };
	//ComponentMgr에서 저장할때 영원히 저장할건지 스테이지마다 버려줄건지
	enum RESOURCETYPE { RESOURCE_STATIC, RESOURCE_STAGE, RESOURCE_END };

	enum BUFFERID { BUFFER_TRICOL, BUFFER_RCTEX, BUFFER_CUBECOL, BUFFER_CUBETEX, BUFFER_TERRAINTEX, BUFFER_SCREENTEX, BUFFER_PARTICLETEX, BUFFER_DYNAMIC };

	enum TEXTURETYPE { TEX_NORMAL, TEX_CUBE, TEX_END };
	//렌더 아이디 - 순서 지정용
	enum RENDERID { RENDER_PRIORITY, RENDER_NONALPHA, RENDER_HDR_ALPHA, RENDER_ALPHA, RENDER_UI, RENDER_END };
	//콜라이더가 부딪혔는지 아닌지 확인
	enum COLLTYPE { COL_FALSE, COL_TRUE, COL_END };
	//메쉬 종류
	enum MESHTYPE { TYPE_STATIC, TYPE_DYNAMIC, TYPE_NAVI, TYPE_NAVI_RUN, MESHTYPE_END };
	// 키보드 or 마우스 눌러서 입력받은 시작키
	enum STARTMOTION { SM_Q, SM_E, SM_R, SM_F, SM_LB, SM_RB, SM_END };
	//마우스 눌렀는지
	enum MOUSEKEYSTATE { DIM_LB, DIM_RB, DIM_MB, DIM_END };
	//마우스 움직임
	enum MOUSEMOVESTATE { DIMS_X, DIMS_Y, DIMS_Z, DIMS_END };
	//Frustum
	enum USEAGE { DISABLE, ENABLE };
	//gameobject가 return 때릴때
	enum GAME_STATE { ERROR_EXIT = -1, NO_EVENT, OBJ_POOL, OBJ_DEAD, CHANGE_SCENE, GAME_STATE_END };
	//레이어 종류
	enum LAYERTYPE { PRIORITY, ENVIRONMENT, GAMEOBJECT, STATICMESH, DYNAMICMESH, NAVIMESH, UI, LAYERTYPE_END };
	//각 gameObejct가 들고있는 컴포넌트의 타입
	enum COMPONENTTYPE { TRANSFORM, CALCULATOR, COLLIDER, RENDERER, OPTIMIZATION, BUFFER, TEXTURE, MESH, NAVI, SHADER, SHADER2, COMPONENTTYPE_END };
	//옵저버가 보고 있는 주체
	enum SUBJECTTYPE { PLAYER, APOSTLE, MATCHING_GMAE, AI_ALLIANCE, AI_ENEMY_1, AI_ENEMY_2, RUNPLAYER, SUBJECTTYPE_END };
	//렌더타겟 종류
	enum RENDERTARGET { PRE_DEPTH,
						ALBEDO, NORMAL, DEPTH, SPECULAR, EMMISIVE, OUTLINE_READY, OUTLINE,
						SHADE, SHADOW_PLAYER, SHADOW_FILTERING,
						BLUR, RADIALBLUR,
						OCCLUSION, OCCLUSION_HORIZONTALBLUR, OCCLUSION_VERTICALBLUR,
						HDR_BASE, LUMINANCE1, LUMINANCE2, LUMINANCE3, LUMINANCE4, LUMINANCE5, LUMINANCE6, BRIGHTPASS, BRIGHTPASSDOWNSAMPLE, HORIZONTALBLUR, VERTICALBLUR, HDRFINISH,
						DOFDOWNSAMPLE, DOFHORIZONTALBLUR, DOFVERTICALBLUR,
						OCCLUSIONSUB, LIGHTSHAFT, FINALIMAGE,
						REFLECT, REFRACT,
						RENDERTARGET_END};
	//렌더타겟 리스트 종류
	enum RENDERTARGETLIST { SHADOW, GEOMETRY, CARTOON, LIGHTACC, HDR, RENDERTARGETLIST_END};
	//네비메쉬 밟으면 어떤 사건이 일어날건지
	enum NAVIMESHTYPE { NONE, TRIGGER, EVENT, NAVIMESHTYPE_END };
	//메쉬들이 가지고있는  Texture들의 타입 -- 수정될수도
	enum MESHTEXTURE_TYPE { MESHTEXTURE_DIFFUSE, MESHTEXTURE_NORMAL, MESHTEXTURE_SPECULAR, MESHTEXTURE_EMMISIVE, MESHTEXTURE_END};
	//왼손에 장착되는 무기인지 오른손에 장착되는 무기인지
	enum HAND { HAND_LEFT, HAND_RIGHT, HAND_END };

	//Skill퀵슬롯에서 쓸 key별 이넘 ->플레이어가 누르는 키와 UI상호작용할 때 쓸 예정 -희정
	enum KEYGUIDE { KEYGUIDE_E, KEYGUIDE_R, KEYGUIDE_F, KEYGUIDE_LSHIFT, KEYGUIDE_TAB, KEYGUIDE_Q, KEYGUIDE_ESC, KEYGUIDE_LB, KEYGUIDE_END };

	//이펙트 생성할때 쓸 이름, 툴에서도 사용
	enum EFFECTTYPE {
		EFFECT_BELATOS_THRUST,
		EFFECT_BELATOS_SHOCKWAVE,
		EFFECT_BELATOS_ARROW,
		EFFECT_BELATOS_CIRCLE,
		EFFECT_BELATOS_SHIELDFRONT,
		EFFECT_BELATOS_CIRCLE2,
		EFFECT_BELATOS_CIRCLE3,
		EFFECT_BELATOS_HEMISPHERE,
		EFFECT_BELATOS_HEMISPHERE2,
		EFFECT_BELATOS_ATTACK,
		EFFECT_BELATOS_SWEEP,
		EFFECT_BELATOS_JUMPLIGHT,
		EFFECT_BELATOS_THRUST2,
		EFFECT_BELATOS_HEMISPHERE3,
		EFFECT_BELATOS_SHOCKWAVE_LAY,
		EFFECT_BELATOS_SHOCKWAVE_LAY2,
		EFFECT_BELATOS_SHOCKWAVE_LAY3,
		EFFECT_BELATOS_SHOCKWAVE2,
		EFFECT_BELATOS_MISSILE,
		EFFECT_19,
		EFFECT_20,
		EFFECT_21,
		EFFECT_22,
		EFFECT_23,
		EFFECT_24,
		EFFECT_25,
		EFFECT_26,
		EFFECT_27,
		EFFECT_28,
		EFFECT_29,
		EFFECT_30,
		EFFECT_31,
		EFFECT_32,
		EFFECT_33,
		EFFECT_34,
		EFFECT_35,
		EFFECT_36,
		EFFECT_37,
		EFFECT_38,
		EFFECT_39,
		EFFECT_40,
		EFFECT_41,
		EFFECT_42,
		EFFECT_43,
		EFFECT_44,
		EFFECT_45,
		EFFECT_46,
		EFFECT_47,
		EFFECT_48_이름변경테스트,
		EFFECT_49_이름변경테스트,
		// 아래서부터 용호 사용
		EFFECT_BASICTRAIL1,
		EFFECT_BASICTRAIL2,
		EFFECT_BASICTRAIL3,
		EFFECT_BASICTRAIL4,
		EFFECT_BASICTRAIL5,
		EFFECT_BASICTRAIL6,
		EFFECT_BASICTRAIL7,
		EFFECT_BASICTRAIL8,
		EFFECT_AIRTRAIL1, //58
		EFFECT_AIRTRAIL2, //59
		EFFECT_AIRTRAIL3, //60
		EFFECT_AIRTRAIL4, //61
		EFFECT_AIRTRAIL5, //62
		EFFECT_AIRBULLET1,
		EFFECT_AIRBULLET2,
		EFFECT_SPEAR,
		EFFECT_SPEAR2,
		EFFECT_AIRUP,
		EFFECT_AIRUP2,
		EFFECT_FATETRAIL1,
		EFFECT_FATETRAIL2,
		EFFECT_FATETRAIL3,
		EFFECT_FATETRAIL4,
		EFFECT_FATETRAIL5,
		EFFECT_FATETRAIL6,
		EFFECT_FATETRAIL7,
		EFFECT_FATETRAIL8,
		EFFECT_FATETRAIL9,
		EFFECT_FATETRAIL10,
		EFFECT_FATE1,
		EFFECT_BLADE1,
		EFFECT_CROSS,
		EFFECT_BASICSP1,
		EFFECT_BASICSP2,
		EFFECT_BASICSP3,
		EFFECT_BASICSP4,
		EFFECT_BASICSP5,
		EFFECT_TEST,
		EFFECT_GENICIDE,
		EFFECT_89,
		EFFECT_90,
		EFFECT_91,
		EFFECT_92,
		EFFECT_93,
		EFFECT_94,
		EFFECT_95,
		EFFECT_96,
		EFFECT_97,
		EFFECT_98,
		EFFECT_99,
		EFFECT_100,
		// 아래부터 시원
		EFFECT_APOSTLE_SPHERE_1,
		EFFECT_APOSTLE_SPHERE_2,
		EFFECT_APOSTLE_SPHERE_3,
		EFFECT_APOSTLE_SPHERE_4,
		EFFECT_APOSTLE_LASER1,
		EFFECT_APOSTLE_SPHERE_5,
		EFFECT_APOSTLE_FAN_TRIANGIE,
		EFFECT_APOSTLE_FAN_HALF,
		EFFECT_APOSTLE_FAN_BIG,
		EFFECT_APOSTLE_TRAIL1,
		EFFECT_APOSTLE_LIGHT,
		EFFECT_APOSTLE_LIGHT2,
		EFFECT_APOSTLE_DOME_HALF,
		EFFECT_APOSTLE_LIGHT_DOT,
		EFFECT_APOSTLE_LIGHT2_DOT,
		EFFECT_116,
		EFFECT_117,
		EFFECT_118,
		EFFECT_119,
		EFFECT_120,
		EFFECT_121,
		EFFECT_122,
		EFFECT_123,
		EFFECT_124,
		EFFECT_125,
		EFFECT_126,
		EFFECT_127,
		EFFECT_128,
		EFFECT_129,
		EFFECT_130,
		EFFECT_131,
		EFFECT_132,
		EFFECT_133,
		EFFECT_134,
		EFFECT_135,
		EFFECT_136,
		EFFECT_137,
		EFFECT_138,
		EFFECT_139,
		EFFECT_140,
		EFFECT_141,
		EFFECT_142,
		EFFECT_143,
		EFFECT_144,
		EFFECT_145,
		EFFECT_146,
		EFFECT_147,
		EFFECT_148,
		EFFECT_149,
		EFFECT_150,
		// 아래부터 희정
		EFFECT_TS_LB, //151  오른쪽(0.4)
		EFFECT_TS_LB_SECOND, //152 동그라미
		EFFECT_TS_AIRLB_SECOND, //153  왼쪽방향
		EFFECT_TS_LB_THIRD1, //154 동그라미 세로로
		EFFECT_TS_LB_THIRD2, //155  151번보다 큰 사이즈(0.7)
		EFFECT_TS_AIRLB_THIRD, //156 공중-3타때 빙글할때
		EFFECT_TS_AIRLB_FOURTH, //157 공중-4타 내려찍기
		EFFECT_TS_RIGHT_MIN, //158 오른쪽키-돌맹이(아래)     :다이나믹매쉬
		EFFECT_TS_RIGHT_MID, //159  오른쪽키-돌맹이 (위)     :다이나믹매쉬
		EFFECT_160,
		EFFECT_TS_LB_PRESSING, //161 왼쪽버튼 꾹 동그라미
		EFFECT_TS_LB_PRESSING2, //162  161다음에나오는 왼쪽, 153보다 더 누워져있음 
		EFFECT_TS_LB_AIRUP, //163 공중띄우기 오른쪽버튼단계  동그라미 세로로(154보다 더 일자)
		EFFECT_TS_E_FIRST, //164 E 스킬-오(죽는속도 0.35)
		EFFECT_TS_E_SECOND, //165 E 스킬-왼(죽는속도 0.35)
		EFFECT_TS_E_THIRD, //166 E 스킬-오(죽는속도 0.2)
		EFFECT_TS_E_FOURTH, //167 E 스킬-왼(죽는속도 0.2)
		EFFECT_TS_R1, //168 R 스킬 - 돌맹이 1종 (enum- 174,175,176)
		EFFECT_TS_F,  //169 F 스킬 - 돌맹이 길 3줄 :다이나믹매쉬
		EFFECT_TS_F_ROCK, //170
		EFFECT_TS_F_ROCKBROKEN, //171 :다이나믹매쉬
		EFFECT_TS_AIRROCK_MIN, //172 공중- 4타(내려찍기) 후 나오는 돌맹이(아래)     :다이나믹매쉬
		EFFECT_TS_AIRROCK_MID, //173 공중- 4타(내려찍기) 후 나오는 돌맹이 (위)     :다이나믹매쉬
		EFFECT_TS_R2, //174 R 스킬 - 돌맹이 1종
		EFFECT_TS_R3, //175 R 스킬 - 돌맹이 1종
		EFFECT_TS_R4, //176 R 스킬 - 돌맹이 1종
		EFFECT_TS_LB_SECOND_ULTIMATE, //177 ) 152번보다 큰 사이즈()
		EFFECT_TS_AIRLB_SECOND_ULTIMATE, //178 ) 153번보다 큰 사이즈()
		EFFECT_TS_LB_THIRD1_ULTIMATE, //179 ) 154번보다 큰 사이즈()
		EFFECT_TS_LB_THIRD2_ULTIMATE, //180 ) 155번보다 큰 사이즈()
		EFFECT_TS_AIRLB_THIRD_ULTIMATE, //181 ) 156번보다 큰 사이즈()
		EFFECT_TS_AIRLB_FOURTH_ULTIMATE, //182 ) 157번보다 큰 사이즈()
		EFFECT_TS_LB_PRESSING_ULTIMATE, //183 ) 161번보다 큰 사이즈()
		EFFECT_TS_LB_PRESSING2_ULTIMATE, //184 ) 162번보다 큰 사이즈()
		EFFECT_TS_LB_AIRUP_ULTIMATE, //185 ) 163번보다 큰 사이즈()
		EFFECT_TS_E_FIRST_ULTIMATE, //186 ) 164번보다 큰 사이즈()
		EFFECT_TS_E_SECOND_ULTIMATE, //187 ) 165번보다 큰 사이즈()
		EFFECT_TS_E_THIRD_ULTIMATE, //188 ) 166번보다 큰 사이즈()
		EFFECT_TS_E_FOURTH_ULTIMATE, //189 ) 167번보다 큰 사이즈()
		EFFECT_TS_LB_ULTIMATE, //190 ) 151번보다 큰 사이즈()
		EFFECT_TS_LAY, //191 빔
		EFFECT_192,
		EFFECT_193,
		EFFECT_194,
		EFFECT_195,
		EFFECT_196,
		EFFECT_197,
		EFFECT_198,
		EFFECT_199,
		// 아래부터 인균
		EFFECT_200,
		EFFECT_WIND_DUST, // 활 F 스킬쓸때 색깔 이펙트
		EFFECT_BOW_RING, // 활 쏠때 이펙트
		EFFECT_DUST, // 활 F 스킬 쓸대 먼지
		EFFECT_ARROW_AURA, // 화살에 붙어있는 아우라
		EFFECT_PHOENIX_WIND1,
		EFFECT_PHOENIX_WIND2,
		EFFECT_PHOENIX_WIND3, //이거만 쓸듯
		EFFECT_ORB_TRAIL, // 오브 우클릭 트레일
		EFFECT_ORB_TRAIL2,//오브 우클릭 트레일
		EFFECT_ORB_WIND, //오브 F 바람
		EFFECT_FIREBALL_WIND, //기모을때 바람
		EFFECT_ORB_WIND2, // 오브 F 바람2
		EFFECT_ORB_BEAM, //오브 F스킬
		EFFECT_ORB_R_PRE,
		EFFECT_ORB_WIND3,
		EFFECT_ORB_WIND4,
		EFFECT_ORB_ULT_WIND,
		EFFECT_ARROW,
		EFFECT_ORB,
		EFFECT_PHOENIX,
		EFFECT_ORB_R_BIG,
		EFFECT_ORB_ULT_BIG,
		EFFECT_ORB_FLARE_BOMB,
		EFFECT_224,
		EFFECT_225,
		EFFECT_226,
		EFFECT_227,
		EFFECT_228,
		EFFECT_229,
		EFFECT_230,
		EFFECT_231,
		EFFECT_232,
		EFFECT_233,
		EFFECT_234,
		EFFECT_235,
		EFFECT_236,
		EFFECT_237,
		EFFECT_238,
		EFFECT_239,
		EFFECT_240,
		EFFECT_241,
		EFFECT_242,
		EFFECT_243,
		EFFECT_244,
		EFFECT_245,
		EFFECT_246,
		EFFECT_247,
		EFFECT_248,
		EFFECT_249,
		EFFECT_250,
		EFFECT_251,
		EFFECT_252,
		EFFECT_253,
		EFFECT_254,
		EFFECT_255,
		EFFECT_256,
		EFFECT_257,
		EFFECT_258,
		EFFECT_259,
		EFFECT_END,
	};
}

#endif // Engine_Enum_h__
