//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// Tool.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_ToolTYPE                    130
#define IDD_MYFORM                      310
#define IDD_MAPTOOL                     311
#define IDD_MESHTOOL                    312
#define IDD_NAVIGATIONTOOL              313
#define IDD_EFFECTTOOL                  314
#define IDD_COLLIDERTOOL                315
#define IDD_PATHFINDTOOL                316
#define IDD_RUNTOOL                     317
#define IDD_CAMTOOL                     320
#define IDC_TAB1                        1000
#define IDC_TREE1                       1002
#define IDC_RADIO1                      1004
#define IDC_RADIO2                      1005
#define IDC_RADIO3                      1006
#define IDC_RADIO4                      1007
#define IDC_RADIO5                      1008
#define IDC_RADIO6                      1009
#define IDC_RADIO7                      1010
#define IDC_RADIO8                      1011
#define IDC_EDIT2                       1018
#define IDC_EDIT3                       1019
#define IDC_EDIT4                       1020
#define IDC_EDIT5                       1021
#define IDC_EDIT6                       1022
#define IDC_EDIT7                       1023
#define IDC_EDIT8                       1024
#define IDC_BUTTON1                     1025
#define IDC_BUTTON2                     1026
#define IDC_LIST1                       1027
#define IDC_BUTTON15                    1027
#define IDC_LIST2                       1028
#define IDC_BUTTON_PAUSE                1028
#define IDC_BUTTON9                     1029
#define IDC_LIST3                       1029
#define IDC_BUTTON_SCENE_CLEAR          1029
#define IDC_BUTTON10                    1030
#define IDC_BUTTON_STOP                 1030
#define IDC_EDIT9                       1031
#define IDC_BUTTON16                    1031
#define IDC_EDIT10                      1032
#define IDC_EDIT11                      1033
#define IDC_BUTTON_DELETE_STATICMESH    1033
#define IDC_BUTTON3                     1034
#define IDC_EDIT12                      1034
#define IDC_BUTTON_ADD_MESH             1034
#define IDC_BUTTON4                     1035
#define IDC_EDIT13                      1035
#define IDC_BUTTON_DELETE_DYNAMICMESH   1035
#define IDC_BUTTON5                     1036
#define IDC_BUTTON_POS_APPLY            1036
#define IDC_LIST5                       1036
#define IDC_EDIT14                      1037
#define IDC_BUTTON7                     1037
#define IDC_LIST_STATICMESH             1037
#define IDC_LIST6                       1037
#define IDC_BUTTON6                     1038
#define IDC_LIST_DYNAMICMESH            1038
#define IDC_BUTTON8                     1039
#define IDC_BUTTON_ADD_TEXTURE          1039
#define IDC_BUTTON11                    1040
#define IDC_BUTTON_DELETE_TEXTURE       1040
#define IDC_BUTTON12                    1041
#define IDC_BUTTON_UVPOS_APPLY          1041
#define IDC_BUTTON13                    1042
#define IDC_BUTTON_ATLAS_APPLY          1042
#define IDC_BUTTON14                    1043
#define IDC_BUTTON_ROT_APPLY            1043
#define IDC_EDIT19                      1043
#define IDC_EDIT1                       1044
#define IDC_LIST_TEXTURE                1044
#define IDC_EDIT20                      1044
#define IDC_EDIT15                      1045
#define IDC_EDIT_POSX                   1045
#define IDC_COMBO1                      1046
#define IDC_EDIT_POSY                   1046
#define IDC_EDIT16                      1046
#define IDC_EDIT_POSZ                   1047
#define IDC_EDIT17                      1047
#define IDC_LIST4                       1048
#define IDC_EDIT18                      1048
#define IDC_BUTTON_SAVE                 1049
#define IDC_BUTTON_LOAD                 1050
#define IDC_BUTTON_START                1051
#define IDC_BUTTON_ADD_TEXTURE_OBJ      1052
#define IDC_SPIN_POS_X                  1053
#define IDC_LIST_TEXTURE_OBJ            1054
#define IDC_BUTTON_DELETE_TEXTURE_OBJ   1055
#define IDC_BUTTON_MOVE_POS_APPLY       1056
#define IDC_CHECK_ATLAS                 1057
#define IDC_CHECK_UVPOS                 1058
#define IDC_EDIT_ROTX                   1059
#define IDC_EDIT_SCALEX                 1060
#define IDC_EDIT_ROTY                   1061
#define IDC_EDIT_ROTZ                   1062
#define IDC_EDIT_SCALEY                 1063
#define IDC_EDIT_SCALEZ                 1064
#define IDC_BUTTON_SCALE_APPLY          1065
#define IDC_EDIT_UVPOSU                 1066
#define IDC_EDIT_UVPOSV                 1067
#define IDC_EDIT_ATLAS_U                1068
#define IDC_EDIT_ATLAS_V                1069
#define IDC_SPIN_POS_Y                  1070
#define IDC_SPIN_POS_Z                  1071
#define IDC_SPIN_ROT_X                  1072
#define IDC_SPIN_ROT_Y                  1073
#define IDC_SPIN_ROT_Z                  1074
#define IDC_SPIN_ATLAS_U                1075
#define IDC_SPIN_SCALE_X                1076
#define IDC_SPIN_SCALE_Y                1077
#define IDC_SPIN_SCALE_Z                1078
#define IDC_SPIN_UVPOS_U                1079
#define IDC_SPIN_UVPOS_V                1080
#define IDC_SPIN_ATLAS_V                1081
#define IDC_EDIT_MOVE_POS_X             1082
#define IDC_EDIT_MOVE_POS_Y             1083
#define IDC_EDIT_MOVE_POS_Z             1084
#define IDC_EDIT_MOVE_ROT_X             1085
#define IDC_EDIT_MOVE_ROT_Y             1086
#define IDC_EDIT_MOVE_ROT_Z             1087
#define IDC_EDIT_MOVE_SCALE_X           1088
#define IDC_EDIT_MOVE_SCALE_Y           1089
#define IDC_EDIT_MOVE_SCALE_Z           1090
#define IDC_SPIN_MOVEPOS_Y              1091
#define IDC_SPIN_MOVEPOS_Z              1092
#define IDC_SPIN_MOVESCALE_Z            1093
#define IDC_SPIN_MOVEPOS_X              1094
#define IDC_SPIN_MOVEROT_X              1095
#define IDC_SPIN_MOVEROT_Y              1096
#define IDC_SPIN_MOVEROT_Z              1097
#define IDC_SPIN_MOVESCALE_X            1098
#define IDC_SPIN_MOVESCALE_Y            1099
#define IDC_EDIT_MOVE_UV_U              1100
#define IDC_BUTTON_MOVE_ROT_APPLY       1101
#define IDC_EDIT_MOVE_UV_V              1102
#define IDC_SPIN_MOVEUV_V               1103
#define IDC_SPIN_MOVEUV_U               1104
#define IDC_EDIT_BEGINTIME_START        1105
#define IDC_EDIT_BEGINTIME_END          1106
#define IDC_SPIN_TIMEBEGIN              1107
#define IDC_SPIN_TIMEEND                1108
#define IDC_BUTTON_MOVE_SCALE_APPLY     1109
#define IDC_BUTTON_MOVE_UV_APPLY        1110
#define IDC_BUTTON_TIME_APPLY           1111
#define IDC_BUTTON_ALL_APPLY            1111
#define IDC_RADIO_ALPHA                 1112
#define IDC_RADIO_NONALPHA              1113
#define IDC_TREE_MESHLIST               1114
#define IDC_TREE_TEXTURE                1115
#define IDC_TREE_TEXTURE_OBJ            1116
#define IDC_EDIT_PASS                   1117
#define IDC_SPIN_PASS                   1118
#define IDC_EDIT_OBJTIME_END            1119
#define IDC_SPIN_OBJTIME_END            1120
#define IDC_COMBO2                      1121
#define IDC_EDIT_SPEED                  1122
#define IDC_SPIN_SPEED                  1123
#define IDC_SPIN1                       1124
#define IDC_SPIN2                       1125
#define IDC_BUTTON17                    1125
#define IDC_SPIN3                       1126
#define IDC_BUTTON18                    1126
#define IDC_SPIN4                       1127
#define IDC_BUTTON_DELETE               1127
#define IDC_BUTTON_RESET                1128

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        323
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1129
#define _APS_NEXT_SYMED_VALUE           318
#endif
#endif
