#ifndef Enum_h__
#define Enum_h__

enum RESOURCETYPE { RESOURCE_STATIC, RESOURCE_STAGE, RESOURCE_END };
enum LOADINGID  { LOADING_STAGE, LOADING_BOSS, LOADING_END };
//enum TOOL_LAYERTYPE {PRIORITY, ENVIRONMENT, GAMEOBJECT, STATICMESH, DYNAMICMESH, NAVIMESH, TOOL_LAYERTYPE_END};
#endif // Enum_h__
